// src/App.tsx
import React, { useState } from 'react';
import { BrowserRouter as Router, Routes, Route } from 'react-router-dom';
import Comics from './components/Comics';
import './App.css';

const App: React.FC = () => {
  const [showNavigation, setShowNavigation] = useState(false);
  const [showSidepanel, setShowSidepanel] = useState(false);

  const navigationItems = [
    { title: 'Quadrinhos', icon: '📚' },
    { title: 'Personagens', icon: '👤' },
    { title: 'Criadores', icon: '👥' },
    { title: 'Eventos', icon: '📅' },
    { title: 'Series', icon: '📖' },
    { title: 'Histórias', icon: '📚' }
  ];

  return (
    <Router>
      <div className="page-container">
        {/* Navbar */}
        <nav className="navbar">
          <div className="navbar-content">
            <button 
              className="navbar-button"
              onClick={() => setShowNavigation(true)}
            >
              ☰ Menu
            </button>
            <h1 className="navbar-title">Loja de HQ</h1>
            <button 
              className="navbar-button"
              onClick={() => setShowSidepanel(true)}
            >
              Favoritos
            </button>
          </div>
        </nav>

        {/* Navigation Drawer */}
        {showNavigation && (
          <div className="drawer-overlay" onClick={() => setShowNavigation(false)}>
            <div className="drawer" onClick={(e) => e.stopPropagation()}>
              <div className="drawer-header">
                <h2>Menu</h2>
                <button 
                  className="drawer-close"
                  onClick={() => setShowNavigation(false)}
                >
                  ✕
                </button>
              </div>
              <ul className="drawer-list">
                {navigationItems.map((item, index) => (
                  <li key={index} className="drawer-item">
                    <span className="drawer-icon">{item.icon}</span>
                    <span>{item.title}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        )}

        {/* Side Panel */}
        {showSidepanel && (
          <div className="drawer-overlay" onClick={() => setShowSidepanel(false)}>
            <div className="drawer drawer-right" onClick={(e) => e.stopPropagation()}>
              <div className="drawer-header">
                <h2>Favoritos</h2>
                <button 
                  className="drawer-close"
                  onClick={() => setShowSidepanel(false)}
                >
                  ✕
                </button>
              </div>
              <ul className="drawer-list">
                <li className="drawer-item">
                  <span>Abbey Christansen</span>
                  <button className="drawer-action">💬</button>
                </li>
                <li className="drawer-item">
                  <span>Alex Nelson</span>
                  <button className="drawer-action">💬</button>
                </li>
                <li className="drawer-item">
                  <span>Mary Johnson</span>
                  <button className="drawer-action">💬</button>
                </li>
              </ul>
            </div>
          </div>
        )}

        {/* Main Content */}
        <main className="main-content">
          <Routes>
            <Route path="/" element={<Comics />} />
          </Routes>
        </main>
      </div>
    </Router>
  );
};

export default App;

// src/App.vue
<template>
  <v-app>
    <div class="page-container md-layout-column">
      <md-toolbar class="md-primary">
        <md-button class="md-icon-button" @click="showNavigation = true">
          <md-icon>menu</md-icon>
        </md-button>
        <span class="md-title">My Title</span>

        <div class="md-toolbar-section-end">
          <md-button @click="showSidepanel = true">Favorites</md-button>
        </div>
      </md-toolbar>

      <md-drawer :md-active.sync="showNavigation" md-swipeable>
        <md-toolbar class="md-transparent" md-elevation="0">
          <span class="md-title">My App name</span>
        </md-toolbar>

        <md-list>
          <md-list-item>
            <md-icon>move_to_inbox</md-icon>
            <span class="md-list-item-text">Inbox</span>
          </md-list-item>

          <md-list-item>
            <md-icon>send</md-icon>
            <span class="md-list-item-text">Sent Mail</span>
          </md-list-item>

          <md-list-item>
            <md-icon>delete</md-icon>
            <span class="md-list-item-text">Trash</span>
          </md-list-item>

          <md-list-item>
            <md-icon>error</md-icon>
            <span class="md-list-item-text">Spam</span>
          </md-list-item>
        </md-list>
      </md-drawer>

      <md-drawer class="md-right" :md-active.sync="showSidepanel">
        <md-toolbar class="md-transparent" md-elevation="0">
          <span class="md-title">Favorites</span>
        </md-toolbar>

        <md-list>
          <md-list-item>
            <span class="md-list-item-text">Abbey Christansen</span>

            <md-button class="md-icon-button md-list-action">
              <md-icon class="md-primary">chat_bubble</md-icon>
            </md-button>
          </md-list-item>

          <md-list-item>
            <span class="md-list-item-text">Alex Nelson</span>

            <md-button class="md-icon-button md-list-action">
              <md-icon class="md-primary">chat_bubble</md-icon>
            </md-button>
          </md-list-item>

          <md-list-item>
            <span class="md-list-item-text">Mary Johnson</span>

            <md-button class="md-icon-button md-list-action">
              <md-icon>chat_bubble</md-icon>
            </md-button>
          </md-list-item>
        </md-list>
      </md-drawer>
      <v-content transition="slide-x-transition">
        <v-container>
          <router-view />
        </v-container>
      </v-content>
    </div>
  </v-app>
</template>

<script>
export default {
  name: 'App',
  data: () => {
    return {
      drawer: true,
      items: [
        { title: 'Quadrinhos', icon: 'mdi-book-open' },
        { title: 'Personagens', icon: 'mdi-human' },
        { title: 'Criadores', icon: 'mdi-human-male-female' },
        { title: 'Eventos', icon: 'mdi-calendar-multiple' },
        { title: 'Series', icon: 'mdi-book-multiple-variant' },
        { title: 'Histórias', icon: 'mdi-book-multiple' }
      ],
      right: true,
      expandOnHover: true,
      showNavigation: false,
      showSidepanel: false
    };
  }
};
</script>
